"""add_homework_workflow_tables

Revision ID: 3214af34e843
Revises: f3c4d5e6a7b8
Create Date: 2026-07-20 13:15:28.810474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3214af34e843'
down_revision: Union[str, None] = 'f3c4d5e6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_misconceptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('misconception_tag', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'misconception_tag', name='uq_problem_misconception')
    )
    op.create_index(op.f('ix_problem_misconceptions_misconception_tag'), 'problem_misconceptions', ['misconception_tag'], unique=False)
    op.create_index(op.f('ix_problem_misconceptions_problem_id'), 'problem_misconceptions', ['problem_id'], unique=False)
    op.create_table('student_homework_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('weekly_target_id', sa.Uuid(), nullable=False),
    sa.Column('mp_status', sa.String(length=20), nullable=False),
    sa.Column('ps_status', sa.String(length=20), nullable=False),
    sa.Column('mp_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mp_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ps_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ps_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weekly_target_id'], ['weekly_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'weekly_target_id', name='uq_user_weekly_target_progress')
    )
    op.create_index(op.f('ix_student_homework_progress_user_id'), 'student_homework_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_student_homework_progress_weekly_target_id'), 'student_homework_progress', ['weekly_target_id'], unique=False)
    op.create_table('student_mp_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('weekly_target_id', sa.Uuid(), nullable=False),
    sa.Column('misconception_question_id', sa.Uuid(), nullable=False),
    sa.Column('misconception_tag', sa.String(length=10), nullable=False),
    sa.Column('selected_option', sa.String(length=1), nullable=False),
    sa.Column('text_input', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['misconception_question_id'], ['misconception_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weekly_target_id'], ['weekly_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mp_attempts_user_weekly', 'student_mp_attempts', ['user_id', 'weekly_target_id'], unique=False)
    op.create_index(op.f('ix_student_mp_attempts_user_id'), 'student_mp_attempts', ['user_id'], unique=False)
    op.create_index(op.f('ix_student_mp_attempts_weekly_target_id'), 'student_mp_attempts', ['weekly_target_id'], unique=False)
    op.create_table('student_mp_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('weekly_target_id', sa.Uuid(), nullable=False),
    sa.Column('tag_queue', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('current_question_id', sa.Uuid(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('attempts_on_current', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_question_id'], ['misconception_questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weekly_target_id'], ['weekly_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'weekly_target_id', name='uq_user_weekly_target_mp_session')
    )
    op.create_index(op.f('ix_student_mp_sessions_user_id'), 'student_mp_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_student_mp_sessions_weekly_target_id'), 'student_mp_sessions', ['weekly_target_id'], unique=False)
    op.create_table('weekly_class_summary_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('weekly_target_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mp_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ps_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_attempts_made', sa.Integer(), nullable=False),
    sa.Column('misconceptions_triggered_count', sa.Integer(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weekly_target_id'], ['weekly_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weekly_target_id', 'user_id', name='uq_weekly_class_summary')
    )
    op.create_index(op.f('ix_weekly_class_summary_reports_user_id'), 'weekly_class_summary_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_weekly_class_summary_reports_weekly_target_id'), 'weekly_class_summary_reports', ['weekly_target_id'], unique=False)
    op.create_table('xlsx_uploads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_misconception_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('misconception_tag', sa.String(length=10), nullable=False),
    sa.Column('triggered', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_student_misc_rec_lookup', 'student_misconception_records', ['user_id', 'problem_id', 'misconception_tag'], unique=False)
    op.create_index(op.f('ix_student_misconception_records_attempt_id'), 'student_misconception_records', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_student_misconception_records_problem_id'), 'student_misconception_records', ['problem_id'], unique=False)
    op.create_index(op.f('ix_student_misconception_records_user_id'), 'student_misconception_records', ['user_id'], unique=False)
    op.drop_index(op.f('ix_misconception_questions_tag'), table_name='misconception_questions')
    op.create_index(op.f('ix_misconception_questions_misconception_tag'), 'misconception_questions', ['misconception_tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_misconception_questions_misconception_tag'), table_name='misconception_questions')
    op.create_index(op.f('ix_misconception_questions_tag'), 'misconception_questions', ['misconception_tag'], unique=False)
    op.drop_index(op.f('ix_student_misconception_records_user_id'), table_name='student_misconception_records')
    op.drop_index(op.f('ix_student_misconception_records_problem_id'), table_name='student_misconception_records')
    op.drop_index(op.f('ix_student_misconception_records_attempt_id'), table_name='student_misconception_records')
    op.drop_index('idx_student_misc_rec_lookup', table_name='student_misconception_records')
    op.drop_table('student_misconception_records')
    op.drop_table('xlsx_uploads')
    op.drop_index(op.f('ix_weekly_class_summary_reports_weekly_target_id'), table_name='weekly_class_summary_reports')
    op.drop_index(op.f('ix_weekly_class_summary_reports_user_id'), table_name='weekly_class_summary_reports')
    op.drop_table('weekly_class_summary_reports')
    op.drop_index(op.f('ix_student_mp_sessions_weekly_target_id'), table_name='student_mp_sessions')
    op.drop_index(op.f('ix_student_mp_sessions_user_id'), table_name='student_mp_sessions')
    op.drop_table('student_mp_sessions')
    op.drop_index(op.f('ix_student_mp_attempts_weekly_target_id'), table_name='student_mp_attempts')
    op.drop_index(op.f('ix_student_mp_attempts_user_id'), table_name='student_mp_attempts')
    op.drop_index('idx_mp_attempts_user_weekly', table_name='student_mp_attempts')
    op.drop_table('student_mp_attempts')
    op.drop_index(op.f('ix_student_homework_progress_weekly_target_id'), table_name='student_homework_progress')
    op.drop_index(op.f('ix_student_homework_progress_user_id'), table_name='student_homework_progress')
    op.drop_table('student_homework_progress')
    op.drop_index(op.f('ix_problem_misconceptions_problem_id'), table_name='problem_misconceptions')
    op.drop_index(op.f('ix_problem_misconceptions_misconception_tag'), table_name='problem_misconceptions')
    op.drop_table('problem_misconceptions')
    # ### end Alembic commands ###
