"""add_indexes_and_constraints

Revision ID: 37bb69e7de12
Revises: c7d3e4f5a6b1
Create Date: 2026-06-27 15:06:20.083312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37bb69e7de12'
down_revision: Union[str, None] = 'c7d3e4f5a6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attempts_user_id'), 'attempts', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_problem_quiz_progress', 'quiz_progress', ['user_id', 'problem_key'])
    op.create_index('idx_student_model_user_updated', 'student_model_states', ['user_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_student_model_states_user_id'), 'student_model_states', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_model_states_user_id'), table_name='student_model_states')
    op.drop_index('idx_student_model_user_updated', table_name='student_model_states')
    op.drop_constraint('uq_user_problem_quiz_progress', 'quiz_progress', type_='unique')
    op.drop_index(op.f('ix_attempts_user_id'), table_name='attempts')
    # ### end Alembic commands ###
