"""add code column to misconception_catalog

Revision ID: 3a84c1e1d0cc
Revises: 8321138f94e5
Create Date: 2026-07-08 13:37:17.842801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3a84c1e1d0cc'
down_revision: Union[str, None] = '8321138f94e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('misconception_catalog', sa.Column('code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('misconception_catalog', 'code')
    # ### end Alembic commands ###
