"""split_description_to_languages

Revision ID: 65f424c7c093
Revises: 37bb69e7de12
Create Date: 2026-06-30 11:12:42.921136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f424c7c093'
down_revision: Union[str, None] = '37bb69e7de12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE problems CASCADE")
    op.add_column('problems', sa.Column('description_en', sa.Text(), nullable=False))
    op.add_column('problems', sa.Column('description_id', sa.Text(), nullable=False))
    op.drop_column('problems', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('problems', 'description_id')
    op.drop_column('problems', 'description_en')
    # ### end Alembic commands ###
