"""add wrong_example and correct_example column to misconception_catalog

Revision ID: 79cefb6c6a79
Revises: 3a84c1e1d0cc
Create Date: 2026-07-08 18:20:49.613242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '79cefb6c6a79'
down_revision: Union[str, None] = '3a84c1e1d0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('misconception_catalog', sa.Column('wrong_example', sa.Text(), nullable=True))
    op.add_column('misconception_catalog', sa.Column('correct_example', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('misconception_catalog', 'correct_example')
    op.drop_column('misconception_catalog', 'wrong_example')
    # ### end Alembic commands ###
