"""add_deadline_and_quiz

Revision ID: b5aeab3f9418
Revises: aea206355578
Create Date: 2026-06-27 11:07:20.933568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5aeab3f9418'
down_revision: Union[str, None] = 'aea206355578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hint_quiz_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('problem_key', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answer', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hint_quiz_questions_problem_key'), 'hint_quiz_questions', ['problem_key'], unique=False)
    op.add_column('weekly_targets', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('weekly_targets', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('weekly_targets', sa.Column('deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_targets', 'deadline')
    op.drop_column('weekly_targets', 'description')
    op.drop_column('weekly_targets', 'title')
    op.drop_index(op.f('ix_hint_quiz_questions_problem_key'), table_name='hint_quiz_questions')
    op.drop_table('hint_quiz_questions')
    # ### end Alembic commands ###
